-- CREATE TABLE users
-- (
--     id         SERIAL PRIMARY KEY,
--     login   VARCHAR(50)  NOT NULL,
--     email      VARCHAR(100) NOT NULL,
--     password   VARCHAR(100) NOT NULL,
--     creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
--
